' <auto-generated />
Imports System
Imports MediaMaster.Data
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic

Namespace Global.MediaMaster.Data.Migrations
    <DbContext(GetType(MediaMasterDbContext))>
    <Migration("20260702191619_InitialCreate")>
    Partial Class InitialCreate
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11")

            modelBuilder.Entity("MediaMaster.Data.Entities.Edition",
                Sub(b)
                    b.Property(Of Integer)("EditionsID").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Description").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Name").
                        HasColumnType("TEXT")

                    b.HasKey("EditionsID")

                    b.ToTable("Editions")
                End Sub)

            modelBuilder.Entity("MediaMaster.Data.Entities.Filter",
                Sub(b)
                    b.Property(Of Integer)("FiltersID").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("FilterValue").
                        HasColumnType("TEXT")

                    b.Property(Of String)("NewValue").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("PartOfText").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Remark").
                        HasColumnType("TEXT")

                    b.Property(Of Boolean)("ReplaceText").
                        HasColumnType("INTEGER")

                    b.HasKey("FiltersID")

                    b.ToTable("Filters")
                End Sub)

            modelBuilder.Entity("MediaMaster.Data.Entities.MusicLogEntry",
                Sub(b)
                    b.Property(Of Integer)("MusicLogID").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Album").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Artist").
                        HasColumnType("TEXT")

                    b.Property(Of DateOnly)("DateStamp").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("DayNumber").
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("EditionsID").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Isrc").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Label").
                        HasColumnType("TEXT")

                    b.Property(Of TimeOnly)("TimeStamp").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Title").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("Year").
                        HasColumnType("INTEGER")

                    b.HasKey("MusicLogID")

                    b.ToTable("MusicLog")
                End Sub)

            modelBuilder.Entity("MediaMaster.Data.Entities.TrafficInfo",
                Sub(b)
                    b.Property(Of Integer)("TrafficInfoID").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("DAB").
                        HasColumnType("TEXT")

                    b.Property(Of String)("RDS").
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("SpotID").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("SpotName").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Stream").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Web").
                        HasColumnType("TEXT")

                    b.HasKey("TrafficInfoID")

                    b.ToTable("TrafficInfo")
                End Sub)
        End Sub
    End Class
End Namespace
